import { Geist, Geist_Mono, Didact_Gothic } from "next/font/google";
import Footer from "@/componenet/Footer";
import "./globals.css";
import FloatingNavbar from "@/componenet/Navbar";
const gothicA1 = Didact_Gothic({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-gothic-a1',
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Astroomee",
  description: "Generated by create next app",
  robots :"noindex, nofollow"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gothicA1.variable} antialiased`}
      >
        <FloatingNavbar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
